spring.datasource.url=jdbc:sqlite:C:/Users/Win/Desktop/ExtremeWeather/Info/DataBase/wether_information.db.db
spring.datasource.driver - class - name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

#debug=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLiteDialect

